#! /bin/sh

echo 'apt-get update && apt-get upgrade -y &>/var/log/update_script.log'>~/apt-update.sh
chmod +x ~/apt-update.sh

#
# Add the task to crontab
# run crontab -e
# 0 4 * * 1 root /bin/sh ~/apt-update.sh >>/etc/update_logs
#
